### ISSUE TITLE
Feat: Basic Authentication for Github API

### ISSUE THREAD

**Issue by jSadoski** [hedythedev/starcli#68]
**Description**

At this time, we're having issues hitting rate limits - especially when testing. GitHub only allows 10 requests/minute. [Basic Authentication would allow up to 30/minute](https://docs.github.com/en/rest/reference/search#rate-limit).

**Why is it necessary? (or how would it make it better)**

This is necessary to expand our ability to perform automated tests without those tests failing due to Rate Limit issues.

**how do you think should it be implemented? (If possible)**

I think we should use a username/api key in the request header for [Basic Authentication](https://docs.github.com/en/rest/overview/other-authentication-methods#basic-authentication). We could then just place the appropriate credentials in an environment variable and [use click to access it](https://click.palletsprojects.com/en/7.x/arguments/?highlight=environment%20variables#environment-variables). We could also cache the username/api key, which I presume we would want to do securely... Not sure how to do that without external modules or if our automated testing would support that.

I would love to work on this! I don't know much about the automated PR testing, however. I would need to know if we can run it with the env variable and which account credentials we would use for testing.

**Comment by hedythedev** [comment]
Thanks for putting up the issue, I had been thinking about prompting the user for API token if rate limit is hit and use it with request headers but didn't have the time.  Using environment variables so it can be used in pytests is a great idea! 

We could first implement the checking if rate limit is hit, and prompt the API token from the user, which can be generated from [here](https://github.com/settings/tokens/new?description=starcli&scopes=public_repo) (got the idea from [githunt](https://kamranahmed.info/githunt/) :D), and then use the token to be added in the header param like [this](https://github.com/kamranahmedse/githunt/blob/b72ab1987a2dc8bb9f2883ad1890eb1f73b06e32/src/redux/github/actions.js#L38) (I know it's JavaScript but the header data is the same). Although using username/password instead of a token would also work, not sure which one would be better. 

<details>
<summary>Details of implementation, just for inspiration</summary>
<br>
<ul>
<li>
for prompting we could use <a href="https://rich.readthedocs.io/en/latest/reference/prompt.html"><code>rich.prompt</code></a> for checking length/chars etc
</li>

<li>
it seems that status code 403 is returned when rate limit is hit
</li>
</ul>
<br><br>
</details>

**Comment by jSadoski** [comment]
So I already got a personal token and I was able to use it with the addition of the [requests-oauthlib](https://pypi.org/project/requests-oauthlib/) package, so that works.

Maybe we should just start by making it an option like `--auth username:token`, then we could add the feature with `rich` to prompt once that's built in?
